### ISSUE TITLE
Heapster cannot write to influxDB

### ISSUE THREAD

**Issue by stresler** [kubernetes/heapster#1474]
I have deployed the indicated versions in the master influxdb manifests from here https://github.com/kubernetes/heapster/tree/master/deploy/kube-config/influxdb

heapster:v1.3.0-beta.0 (from gcr.io)

heapster-grafana:v4.0.2 (from makefile)

heapster-influxdb:v1.1.1 (from makefile) (see issue #1453)

Heapster creates the k8s DB in influxdb 
`I0120 20:34:05.196919       1 influxdb.go:209] Created database "k8s" on influxDB server at "heapster-influxdb:8086"`

I can see that heapster (and grafana) can both connect to the container just fine, but for some reason POSTs are getting an HTTP 500 and pings a 204

```
[httpd] 192.168.56.207 - root [20/Jan/2017:20:44:05 +0000] "POST /write?consistency=&db=k8s&precision=&rp=default HTTP/1.1" 500 72 "-" "heapster/v1.3.0-beta.0" 2ece120b-df51-11e6-808e-000000000000 15630
[httpd] 192.168.56.207 - root [20/Jan/2017:20:44:05 +0000] "GET /ping HTTP/1.1" 204 0 "-" "heapster/v1.3.0-beta.0" 2ed087a5-df51-11e6-808f-000000000000 14
```

192.168.56.207 is the heapster pod. 

```
[query] 2017/01/20 20:44:18 SHOW MEASUREMENTS ON k8s
[httpd] 192.168.56.204 - root [20/Jan/2017:20:44:18 +0000] "GET /query?db=k8s&epoch=ms&q=SHOW+MEASUREMENTS HTTP/1.1" 200 46 "http://10.40.16.48:30078/dashboard/new?panelId=1&fullscreen&edit&tab=metrics" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/45.0.2454.101 Chrome/45.0.2454.101 Safari/537.36" 367ca1cd-df51-11e6-8090-000000000000 649
```
192.168.56.204 is grafana successfully querying and getting nothing because there is nothing written there. 

I ran `curl http://192.168.56.206:8086/debug/vars` which returned almost immediately and I see this: 

```
"database:_internal": {"name":"database","tags":{"database":"_internal"},"values":{"numMeasurements":12,"numSeries":12}},
"write": {"name":"write","tags":null,"values":{"pointReq":521793,"pointReqLocal":7710,"req":747,"subWriteDrop":0,"subWriteOk":643,"writeDrop":0,"writeError":0,"writeOk":643,"writeTimeout":0}},
"subscriber": {"name":"subscriber","tags":null,"values":{"pointsWritten":0,"writeFailures":0}},
"cq": {"name":"cq","tags":null,"values":{"queryFail":0,"queryOk":0}},
"httpd::8086": {"name":"httpd","tags":{"bind":":8086"},"values":{"authFail":0,"clientError":0,"pingReq":106,"pointsWrittenDropped":0,"pointsWrittenFail":514083,"pointsWrittenOK":0,"queryReq":43,"queryReqDurationNs":48834315,"queryRespBytes":1286,"req":254,"reqActive":1,"reqDurationNs":1801700459,"serverError":104,"statusReq":0,"writeReq":104,"writeReqActive":0,"writeReqBytes":166444135,"writeReqDurationNs":1728858874
```
Which seems to indicate that the internal db queries execut ejust fine, but every single http write is failing. 

Any support would be welcome. Thanks.

**Comment by jackzampolin** [comment]
It looks like Heapster is writing to the database with `rp=default` This might be the cause of the 500s.  Can you please check and see if you can connect to the database with the `influx` cli and run the following two queries?

```
$ influx -host 192.168.56.206 -port 8086
> SHOW DATABASES
> SHOW RETENTION POLICIES
```

**Comment by stresler** [comment]
Is this what you mean:

```
./influx -host 192.168.56.206 -port 8086
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://192.168.56.206:8086 version unknown
InfluxDB shell version: 1.1.1
> show databases; 
name: databases
name
----
_internal
k8s

> SHOW RETENTION POLICIES
ERR: database name required
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
> use k8s
Using database k8s
> SHOW RETENTION POLICIES
name	duration	shardGroupDuration	replicaN	default
----	--------	------------------	--------	-------
autogen	0s		168h0m0s		1		true
```

**Comment by jackzampolin** [comment]
It looks like the database got created with the `autogen` retention policy instead of the `default` retention policy. You can fix the immediate issue by creating the retention policy. `CREATE RETENTION POLICY default ON k8s DURATION 0d REPLICATION 1 DEFAULT`

**Comment by jackzampolin** [comment]
This issue should be resolved by [#1415](https://github.com/kubernetes/heapster/pull/1415) I just pulled down the latest `master` and all the `CREATE DATABASE` calls for Influx ([here](https://github.com/kubernetes/heapster/blob/master/events/sinks/influxdb/influxdb.go#L191) and [here](https://github.com/kubernetes/heapster/blob/master/metrics/sinks/influxdb/influxdb.go#L202)) explicitly create the `default` retention policy when creating the database.

**Comment by stresler** [comment]
I have done this (default needs to be quoted for anyone else finding this), and grafana has started displaying data. 

Still getting that 204 in logs, but I think I can maybe safely ignore that for now.

**Comment by stresler** [comment]
Thanks!

**Comment by TinySong** [comment]
i get the same issue,  when execute "CREATE RETENTION POLICY default ON k8s DURATION 0d REPLICATION 1 DEFAULT", got another error: ERR: error parsing query: found DEFAULT, expected identifier at line 1, char 25, anyone help me

**Comment by jackzampolin** [comment]
@TinySong You need to submit the query like so:

```
CREATE RETENTION POLICY "default" ON k8s DURATION 0d REPLICATION 1 DEFAULT
```
