### ISSUE TITLE
Connection to kubelet based on IP not hostname

### ISSUE THREAD

**Issue by mwringe** [kubernetes/heapster#663]
There is an issue when connecting to a kubelet endpoint over tls where the certificate used is based on hostname and not ip address.

When trying to connect to a kubelet endpoint in this situation, heapster will fail to connect and throw the following error:

1 kubelet.go:96] failed to get stats from kubelet url: https://192.168.122.1:10250/stats/metrics/hawkular-metrics-tbd9b/f00788ca-7760-11e5-99ca-3c970e88a56f/hawkular-metrics - Get https://192.168.122.1:10250/stats/metrics/hawkular-metrics-tbd9b/f00788ca-7760-11e5-99ca-3c970e88a56f/hawkular-metrics: x509: cannot validate certificate for 192.168.122.1 because it doesn't contain any IP SANs

Instead of getting the IP addresses from the Kubernetes master, we should use the hostname instead, or at the very least provide a means of configuring which option to use.

Note that using `insecure` cannot be used as a workaround due to https://github.com/kubernetes/heapster/issues/662

**Comment by jimmidyson** [comment]
@mwringe What does `kubectl get nodes` show?

**Comment by mwringe** [comment]
NAME      LABELS                          STATUS    AGE
mynode    kubernetes.io/hostname=mynode   Ready     18h

**Comment by jimmidyson** [comment]
How about `kubectl get nodes -oyaml`? Just want to think of the best way to get the node address.

**Comment by mwringe** [comment]
Note that it will work if I happen to name my node the same as its IP address (which is why it just happens to work on my machine but not on any others)

**Comment by mwringe** [comment]
The node yaml output:

apiVersion: v1
kind: Node
metadata:
  creationTimestamp: 2015-10-20T19:24:54Z
  labels:
    kubernetes.io/hostname: mynode
  name: mynode
  resourceVersion: "944"
  selfLink: /api/v1/nodes/mynode
  uid: 3e05f4bd-7760-11e5-a89f-3c970e88a56f
spec:
  externalID: mynode
status:
  addresses:
  - address: 192.168.122.1
    type: LegacyHostIP
  - address: 192.168.122.1
    type: InternalIP
  capacity:
    cpu: "4"
    memory: 11997300Ki
    pods: "40"
  conditions:
  - lastHeartbeatTime: 2015-10-21T13:46:35Z
    lastTransitionTime: 2015-10-21T13:01:13Z
    message: kubelet is posting ready status
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  nodeInfo:
    bootID: c8a62c9a-c8b2-4f61-beff-9578eaf25e23
    containerRuntimeVersion: docker://1.8.1.fc21
    kernelVersion: 4.1.6-100.fc21.x86_64
    kubeProxyVersion: v1.2.0-alpha.1-1107-g4c8e6f4
    kubeletVersion: v1.2.0-alpha.1-1107-g4c8e6f4
    machineID: 3cb44cba06684ed79dd063d7fa1734b2
    osImage: Fedora 21 (Twenty One)
    systemUUID: 81DD6B6F-5C52-CB11-B83D-8C85C64DBBDB

The Heapster code looks for the IP address when connecting to the node and not the name

**Comment by jimmidyson** [comment]
@liggitt What do you suggest for this? Node name doesn't have to be a resolvable address afaik & node IP isn't a SAN in node TLS cert.

**Comment by liggitt** [comment]
If the node is accessed by IP, then the IP should be in the node's certificate as a SAN. What setup are you using to create the node's certificate?

**Comment by jimmidyson** [comment]
By default, does kubernetes connect to the node via the IP & does it validate the node certificate?

**Comment by liggitt** [comment]
If a ca is provided to the master for constructing the kubelet client, it verifies the cert. 

It looks like connections to the node are IP based (https://github.com/kubernetes/kubernetes/blob/782102d4370f85228ca6aabbc84b998c266b6e6d/pkg/registry/node/strategy.go#L139)

I am not sure how the various setup scripts invoke the master, if they provide a kubelet CA or not

**Comment by mwringe** [comment]
>What setup are you using to create the node's certificate?

`openshift start --write-config=openshift.local.config --hostname=myNode --public-master=$IP_ADDRESS --master=$IP_ADDRESS`

As a work around, if I set `--hostname=$IP_ADDRESS` then it can connect

**Comment by mvdan** [comment]
Fixed by #664.

**Comment by mwringe** [comment]
I don't believe #664 does not fix this issue, I believe it only allows `insecure` to work with the kubelet endpoint and this is a separate issue.

**Comment by jimmidyson** [comment]
#664 "fixes" it for a cluster that doesn't have certificates correctly set up as you had. Heapster cannot fix up poorly configured clusters but we can work with it...

**Comment by liggitt** [comment]
I'm pretty sure the ansible installer adds the node IP to the serving cert (@sdodson, confirm?). Can you open an issue against openshift origin to fix the write-config option to include the IP?

**Comment by mwringe** [comment]
>#664 "fixes" it for a cluster that doesn't have certificates correctly set up as you had. Heapster cannot fix up poorly configured clusters but we can work with it...

Are we sure this is a broken setup? Not specifying the IP address in a certificate may not be the best idea, but I don't know if I would say its an invalid setup.

**Comment by liggitt** [comment]
> Are we sure this is a broken setup? Not specifying the IP address in a certificate may not be the best idea, but I don't know if I would say its an invalid setup.

There are degrees of invalid. Serving with a cert that doesn't include an address you expect to be contacted on is not a good setup

**Comment by mwringe** [comment]
Ok, makes sense. Do we have a corresponding issue in OpenShift to track this?

**Comment by liggitt** [comment]
Not that I'm aware of. Can you open an issue against openshift origin to add the IP to the node's certificate when running the all-in-one? I think the ansible install already builds the node's serving certificate correctly

**Comment by mwringe** [comment]
@liggitt Ok, I created one here: https://github.com/openshift/origin/issues/5294

**Comment by sdodson** [comment]
> I'm pretty sure the ansible installer adds the node IP to the serving cert (@sdodson, confirm?). Can you open an issue against openshift origin to fix the write-config option to include the IP?

No it does not add the node's ip to the node's serving cert. I've added this to https://github.com/openshift/openshift-ansible/pull/609
