### ISSUE TITLE
heapster comes up before influxdb is ready

### ISSUE THREAD

**Issue by phemmer** [kubernetes/heapster#756]
The guide at https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md provides a command (`kubectl create -f deploy/kube-config/influxdb/`) which brings up all resources near simultaneously. This apparently can cause issues with the heapster pod when it tried to connect to influxdb:

```
I1201 20:32:58.289427       1 heapster.go:61] /heapster --source=kubernetes:https://kubernetes.default --sink=influxdb:http://monitoring-influxdb:8086
I1201 20:32:58.289620       1 heapster.go:62] Heapster version 0.18.0
I1201 20:32:58.290218       1 kube_factory.go:172] Using Kubernetes client with master "https://kubernetes.default" and version "v1"
I1201 20:32:58.290283       1 kube_factory.go:173] Using kubelet port 10255
E1201 20:33:28.294551       1 manager.go:257] encountered following errors while setting up sinks - failed to ping InfluxDB server at "monitoring-influxdb:8086" - Get http://monitoring-influxdb:8086/ping: dial tcp 10.3.0.103:8086: i/o timeout
I1201 20:33:28.298463       1 heapster.go:72] Starting heapster on port 8082
```

This results in grafana throwing 500 errors when it tries to access

     https://kubernetes.example.com/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/api/datasources/proxy/1/query?epoch=ms&q=SELECT+last(value)+FROM+%22memory%2Flimit_bytes_gauge%22+WHERE+%22container_name%22+%3D~+%2F%7B%7D%2F+AND+time+%3E+now()+-+6h+GROUP+BY+time(10s)+fill(null)%0ASELECT+last(value)+FROM+%22memory%2Fusage_bytes_gauge%22+WHERE+%22container_name%22+%3D~+%2F%7B%7D%2F+AND+time+%3E+now()+-+6h+GROUP+BY+time(10s)+fill(null)%0ASELECT+last(value)+FROM+%22memory%2Fworking_set_bytes_gauge%22+WHERE+%22container_name%22+%3D~+%2F%7B%7D%2F+AND+time+%3E+now()+-+6h+GROUP+BY+time(10s)+fill(null)

...since the `k8s` db was never created by heapster.

Restarting the heapster container fixed the issue.

It seems either heapster needs to periodically retry connecting to influxdb, some sort of wait mechanism, or the docs need to be adjusted to not launch them all simultaneously. Though I think the latter isn't a good choice, as I imagine this issue can recur if the heapster & influxdb pods ever go down and come up at the same time (such as a node reboot).

**Comment by vishh** [comment]
This issue is already fixed on HEAD. The next release will fix this issue.

**Comment by mwielgus** [comment]
@vishh It is still not fixed. Moreover there should be retries in the sink.

```
 kubectl logs heapster-v10-o6n83 --namespace=kube-system
I1211 14:33:56.148091       1 heapster.go:61] /heapster --source=kubernetes:'' --sink=influxdb:http://monitoring-influxdb:8086 --stats_resolution=30s --sink_frequency=1m
I1211 14:33:56.148205       1 heapster.go:62] Heapster version 0.19.0
I1211 14:33:56.149073       1 kube_factory.go:172] Using Kubernetes client with master "https://10.0.0.1:443" and version "v1"
I1211 14:33:56.149088       1 kube_factory.go:173] Using kubelet port 10255
E1211 14:34:16.220762       1 manager.go:257] encountered following errors while setting up sinks - failed to ping InfluxDB server at "monitoring-influxdb:8086" - Get http://monitoring-influxdb:8086/ping: dial tcp: lookup monitoring-influxdb: no such host
I1211 14:34:16.223077       1 heapster.go:72] Starting heapster on port 8082
```

**Comment by mwielgus** [comment]
cc: @piosz

**Comment by mwielgus** [comment]
I'm fixing a bunch of issues in influxdb code. The fixing PR should come soon.

**Comment by mwielgus** [comment]
Fixed with #780. 
The fix is available in release v0.19.1.
